# Generated by Django 6.1 on 2026-08-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=300)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
