# Generated by Django 6.1 on 2026-09-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_review_unique_together'),
        ('restaurants', '0003_review'),
    ]

    operations = [
    ]
