# Generated by Django 6.1 on 2026-09-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_openinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ['day']},
        ),
    ]
