# Generated by Django 6.1 on 2026-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_merge_0002_alter_review_unique_together_0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
