# Generated by Django 6.1 on 2026-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends & Family'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
