# Generated by Django 6.1 on 2026-09-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
