# Generated by Django 6.1 on 2026-09-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_cover_photo'),
        ('accounts', '0006_profile_failed_login_attempts_profile_locked_until'),
    ]

    operations = [
    ]
