from pathlib import Path
from decouple import config
import os


BASE_DIR = Path(__file__).resolve().parent.parent


"""
Django settings for cravr_project project.

Generated by 'django-admin startproject' using Django 6.1.
"""


# ==========================================
# Core
# ==========================================

SECRET_KEY = config('SECRET_KEY')

DEBUG = os.environ.get(
    "DEBUG",
    "True"
).lower() == "true"

ALLOWED_HOSTS = ["*"]


# ==========================================
# Applications
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'accounts',
    'restaurants',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]


# ==========================================
# Middleware
# ==========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = 'cravr_project.urls'


# ==========================================
# Templates
# ==========================================

TEMPLATES = [
    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'cravr_project.wsgi.application'


# ==========================================
# Database
# ==========================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / "db.sqlite3",
    }
}


# ==========================================
# Password validation
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================================
# Internationalization
# ==========================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = True


# ==========================================
# Static files
# ==========================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# ==========================================
# Media / user uploads
# ==========================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / "data" / "media"


# ==========================================
# Gmail API
# ==========================================

GMAIL_CLIENT_ID = config(
    'GMAIL_CLIENT_ID'
)

GMAIL_CLIENT_SECRET = config(
    'GMAIL_CLIENT_SECRET'
)

GMAIL_REFRESH_TOKEN = config(
    'GMAIL_REFRESH_TOKEN'
)

GMAIL_SENDER_EMAIL = config(
    'GMAIL_SENDER_EMAIL'
)

DEFAULT_FROM_EMAIL = GMAIL_SENDER_EMAIL


# Django/allauth emails such as Forgot Password
MAILERS = {
    "default": {
        "BACKEND":
            "accounts.gmail_email_backend.GmailAPIEmailBackend",
    },
}


# ==========================================
# Sessions
# ==========================================

SESSION_COOKIE_AGE = 1209600


# ==========================================
# Django Sites
# ==========================================

SITE_ID = 1


# ==========================================
# Authentication
# ==========================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# ==========================================
# Google Login
# ==========================================

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id':
                config('GOOGLE_CLIENT_ID'),

            'secret':
                config('GOOGLE_CLIENT_SECRET'),

            'key': ''
        },

        'SCOPE': [
            'profile',
            'email',
        ],
    }
}


SOCIALACCOUNT_ADAPTER = (
    'accounts.adapter.CustomSocialAccountAdapter'
)

LOGIN_REDIRECT_URL = (
    '/accounts/google-login-redirect/'
)

SOCIALACCOUNT_EMAIL_AUTHENTICATION = False

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True


# ==========================================
# HTTPS / Railway
# ==========================================

SECURE_PROXY_SSL_HEADER = (
    'HTTP_X_FORWARDED_PROTO',
    'https'
)

ACCOUNT_DEFAULT_HTTP_PROTOCOL = (
    'http'
    if DEBUG
    else 'https'
)

USE_X_FORWARDED_HOST = True


CSRF_TRUSTED_ORIGINS = [
    "https://cravr-production.up.railway.app",
]


# ==========================================
# Storage
# ==========================================

STORAGES = {
    "default": {
        "BACKEND":
            "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ==========================================
# Logging
# ==========================================

LOGGING = {
    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "class":
                "logging.StreamHandler",
        },
    },

    "loggers": {
        "django": {
            "handlers": [
                "console"
            ],

            "level":
                "INFO",
        },

        "django.request": {
            "handlers": [
                "console"
            ],

            "level":
                "ERROR",

            "propagate":
                False,
        },
    },
}
